// ========================================
// COUPLE MODE — Content
// ========================================

const WML_QUESTIONS = [
  'Who apologizes first after a fight?',
  'Who gets jealous faster?',
  'Who checks their phone secretly?',
  'Who starts fights then forgets why?',
  'Who would survive a zombie apocalypse?',
  'Who spends more money on food?',
  'Who would cry at a movie first?',
  'Who\'s more likely to cancel plans last minute?',
  'Who talks more during a movie?',
  'Who would panic first in an emergency?',
  'Who stalks the ex\'s Instagram?',
  'Who forgets anniversaries?',
  'Who gets road rage?',
  'Who overthinks everything?',
  'Who\'s the bigger drama queen?',
  'Who would rat out the other to their parents?',
  'Who falls asleep during a date?',
  'Who eats the other\'s food without asking?',
  'Who takes 3x longer to get ready?',
  'Who would flirt back if someone hit on them?',
  'Who\'s more likely to become a villain?',
  'Who would start a cult?',
  'Who cries over a sad reel at 1 AM?',
  'Who would survive a week without their phone?',
];

const RFGF_SCENARIOS = [
  'Partner likes their ex\'s Instagram post.',
  'Partner has a "best friend" you\'ve never met.',
  'Partner goes through your phone while you sleep.',
  'Partner texts their ex on their birthday.',
  'Partner cancels date night for friends.',
  'Partner keeps photos of their ex saved.',
  'Partner forgets your birthday.',
  'Partner is still in a group chat with their ex.',
  'Partner rates someone else attractive in front of you.',
  'Partner talks to their ex \'just as friends\'.',
  'Partner hides their screen when you walk by.',
  'Partner stays late at work with a \'colleague\'.',
  'Partner changes their phone password after a fight.',
  'Partner gets super defensive when you ask who they\'re texting.',
  'Partner still uses their ex\'s nickname for them.',
  'Partner compares you to their ex.',
  'Partner accidentally calls you by the wrong name.',
  'Partner says "it\'s nothing" about something clearly not nothing.',
  'Partner is "just going to hang out" with someone you\'ve never heard of.',
  'Partner suddenly starts working out without telling you why.',
];

const FTS_TEMPLATES = [
  'My partner gets scary when ______',
  'The pettiest thing we\'ve argued about is ______',
  'My partner definitely has a secret obsession with ______',
  'I would never admit this but I actually ______',
  'Our relationship would end if ______',
  'My partner thinks I don\'t know that they ______',
  'The weirdest habit my partner has is ______',
  'If my partner read my search history they\'d ______',
  'The last time I was genuinely annoyed I ______',
  'When we fight my partner always ______',
  'My partner\'s most embarrassing moment was ______',
  'If I could change one thing about my partner I\'d ______',
  'The one thing I\'d never tell my partner\'s parents is ______',
  'My partner would be 10x more attractive if they stopped ______',
  'The reason we actually fight is always ______',
];

const TOS_QUESTIONS = [
  'What was your pettiest reason for a fight?',
  'Who said "I love you" first?',
  'What\'s one thing you\'re jealous of about your partner?',
  'Have you ever checked your partner\'s phone? Be honest.',
  'What\'s the most attractive thing about your partner\'s personality?',
  'What\'s one habit of your partner that drives you crazy?',
  'Describe your partner in 3 words. No lying.',
  'What\'s something you pretend to like that your partner loves?',
  'What\'s the most embarrassing thing your partner has done in public?',
  'Have you ever secretly agreed with someone criticising your partner?',
  'What\'s your partner\'s most annoying trait?',
  'Who loves the other more right now?',
  'What\'s something you keep from your partner to avoid a fight?',
  'Describe the last dream you had about your partner.',
  'What\'s a white lie you\'ve told your partner recently?',
  'What\'s the most irrational thing you\'ve been jealous about?',
  'What\'s something your partner does that you find secretly attractive?',
  'How long did it take you to realize you liked your partner?',
  'What\'s the most romantic thing your partner has done?',
  'What\'s the one argument you keep having over and over?',
];

const TELEPATHY_QUESTIONS = [
  'Best comfort food?',
  'Dream vacation destination?',
  'Ideal date night?',
  'Guilty pleasure film genre?',
  'First thing you\'d buy with ₹1 crore?',
  'The one song that plays in your head on loop?',
  'Your hidden talent?',
  'Weirdest food combo you actually enjoy?',
  'If you were an animal, which one?',
  'What would your reality TV show be called?',
  'Your biggest irrational fear?',
  'One word that describes your relationship?',
  'Dream job if money didn\'t matter?',
  'Most used emoji?',
  'The last thing you Googled that you\'re embarrassed about?',
];

const CAPTION_LABELS = [
  'Angry GF',
  'Sleep-deprived BF',
  'Full Gremlin Mode',
  'Main Character Energy',
  'Unhinged but Valid',
  'Send Help',
  'Certified Goblin',
  'Just Ate Maggi at 3AM',
];

const ROASTS = {
  'Angry GF':             'Your partner has officially filed for emotional bankruptcy. Prayers up. 🙏',
  'Sleep-deprived BF':    'That\'s not a partner, that\'s a house ghost with attachment issues.',
  'Full Gremlin Mode':    'Scientists have confirmed: this is what love looks like after 6 months.',
  'Main Character Energy':'Your partner lives in a coming-of-age film no one asked for.',
  'Unhinged but Valid':   'Chaotic, unhinged, but somehow 100% correct. Respect.',
  'Send Help':            'This portrait is a cry for intervention. We\'ve alerted the authorities.',
  'Certified Goblin':     'Studies show 9/10 partners are goblins. Yours passed with honors.',
  'Just Ate Maggi at 3AM':'Living life one instant noodle at a time. Iconic.',
};

module.exports = {
  WML_QUESTIONS,
  RFGF_SCENARIOS,
  FTS_TEMPLATES,
  TOS_QUESTIONS,
  TELEPATHY_QUESTIONS,
  CAPTION_LABELS,
  ROASTS,
};
